# Generated by Django 4.0.4 on 2022-04-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questiont_text',
            new_name='question_text',
        ),
    ]
